baseURL = "https://lxvm.github.io/ph121c/"
theme = "mytheme"
languageCode = "en"
defaultContentLanguage = "en"
title = "Lorenzo X. Van Muñoz"
publishDir="docs"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
  unsafe = true
